version: "3"
services:

  mysql-app:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: simple_wms
  
  wms-be-app:
    build: .
    ports: 
        - 3000:3000
    depends_on: 
        - mysql-app
    # volumes: 
    #     - $PWD/:/usr/src/app/
  
#buat ngetest phpmyadminnya
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment: 
        PMA_HOST: mysql-app
    ports: 
        - 9090:80
