version: "3"
services:

  mysql: #nama service
    image: mysql:5.7 #images
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password #create password
        MYSQL_DATABASE: simple_wms #create db
  
  wms-be-app:
    build: . #build dir
    ports: 
        - 3000:3000
    depends_on: 
        - mysql
    # volumes: 
    #     - $PWD/:/usr/src/app/ # make volumes
  
#buat ngetest phpmyadminnya
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment: 
        PMA_HOST: mysql
    ports: 
        - 9090:80
